### ISSUE TITLE
[Bug] Slide-to-seek makes the video jump ahead

### ISSUE THREAD

**Issue by novocaiin** [YTVanced/Vanced#1472]
**Bug description:**
Holding to initiate slide-and-seek causes the current position to jump ~a minute ahead.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 12

**Device:**
Google Pixel 5

**Steps to Reproduce**
1. Open a longer video in landscape
2. Long-press to slide-and-seek

**Expected behaviour:**
Slide-and-seek gets initiated from the current timestamp.

https://user-images.githubusercontent.com/95007229/146153842-d2ebaf1c-2e52-4811-8670-7e5204161bf8.mp4

**Comment by milindgoel15** [comment]
It's not a bug. Its YT feature and even happens in official yt

**Comment by novocaiin** [comment]
There is no way that's a feature.
It has absolutely no uses and only introduces frustrations.
I've just checked the official app.
No it doesn't do this.

**Comment by milindgoel15** [comment]
>I've just checked the official app. No it doesn't do this.

it does sir. check ur yt version. if u have an ancient version of yt, then obviously it won't do that. Tested and working on 16.29 till 16.48 of yt

**Comment by milindgoel15** [comment]
Official yt: https://imgur.com/5LVoDTb

**Comment by novocaiin** [comment]
It's not happening for you!

**Comment by novocaiin** [comment]
I'm not seeing the video jumping to a random spot. It's exactly where you want it to be.

Reread my description and rewatch my video please.

**Comment by novocaiin** [comment]
Timestamps of interest: 0:04 0:09 0:14 0:20

**Comment by milindgoel15** [comment]
oopsie, my bad. I mean I did see u were referring to the slide to seek but I didn't see the seek bar down below with which I thought u are talking about why it's doing that. my mistake

Have u tried basic troubleshooting? Clearing data or reinstallation? I did check up on my end and it's not jumping so basic troubleshooting should fix it for you.

Again, huge apologies

**Comment by novocaiin** [comment]
Yup!

The videos are shot on a fresh install, data and cache cleared.

Optimization is disabled for both Vanced and Manager.

**Comment by milindgoel15** [comment]
So it works fine now?

**Comment by novocaiin** [comment]
No no, it's not working.
I was saying that the screen recording is done on a fresh Vanced install with battery optimization disabled, and it's still not working.

**Comment by milindgoel15** [comment]
Try another clean install. The issue is not related to battery optimization. its just google being google

**Comment by novocaiin** [comment]
What do you mean by a google bug?

The official app is working flawlessly for me.
Now I reinstalled both Vanced and Manager, and it straight up crashes before I can even open anything.

Also slide up to enter full screen is pretty glitchy:

https://user-images.githubusercontent.com/95007229/146164507-394a38f1-3fa2-43b1-88fd-a210ed5347ac.mp4

As you can see, it requires that I pull it up super high and flickers during animation.
For the reference here's the official app:

https://user-images.githubusercontent.com/95007229/146164942-115e857c-677b-43d9-a9b8-ce8401ed7a6f.mp4

You only need to pull up slightly and it enters smoothly with no glitches during transition animation.

Generally frequent random crashes out of nowhere while I'm watching a video in Vanced.
I don't even know where to start.
I could open like 5 issues straight off the top of my head 😅

**Comment by milindgoel15** [comment]
> What do you mean by a google bug?
> 
> The official app is working flawlessly for me.

Tell me version of official yt u have?

**Comment by novocaiin** [comment]
16.48

**Comment by milindgoel15** [comment]
> 16.48

And vanced is 16.29 which was built on the v16.29 base of official yt. Thats what google bug means.

**Comment by novocaiin** [comment]
That version seems to be from July of this year. Surely it wasn't that bad even back then.
This is worse than 2013 YouTube on my Galaxy S2 😅

**Comment by milindgoel15** [comment]
2013 youtube != 2021 youtube buddy

Google has ruined youtube more than older times. The last perfect yt version was 14.21.54. 

Anything other than vanced parts is a google problem & ofc we didn't make youtube, google did. And new base update should fix these issues for you.

**Comment by novocaiin** [comment]
How are you testing on official 16.29?
As in, are all the official builds published somewhere?

**Comment by milindgoel15** [comment]
apkmirror has every version u need. Just note that try to reproduce the issue for 2-3 days.

 meanwhile I will have everyone test this issue further to make sure it's actually a base issue.
