### ISSUE TITLE
[Bug] Youtube Vanced uninstalls and sometimes crashes on phone restart

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [YTVanced/Vanced#248]
**Bug description**
Ever since the Vanced 2 Manager, Youtube Vanced has been uninstalling itself whenever I restart my phone. Sometimes I can just reinstall it and it will work fine. Sometimes it will crash on launch no matter what I do and the only fix is to uninstall Youtube Vanced and reinstalling it, causing me to lose all my settings. The crashing might be caused when I restart my phone and launch Youtube before reinstalling Youtube Vanced.

**Variant**
Root: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Oneplus 3

**Steps to Reproduce**
Restart phone.

**Comment by asdsadsaasd12312132** [comment]
The cause of the uninstalling has been found.

**Comment by kyelbek** [comment]
> The cause of the uninstalling has been found.

You should mention what you did to solve this problem, so people can know if same solution works for them.

**Comment by asdsadsaasd12312132** [comment]
> > The cause of the uninstalling has been found.
> 
> You should mention what you did to solve this problem, so people can know if same solution works for them.

I only found the cause (restarting phone) not solution.

**Comment by kyelbek** [comment]
> I only found the cause (restarting phone) not solution.

Whoops, you're right. I read it wrong, my fault. If it comes to these crashes, I made a [PR](https://github.com/YTVanced/VancedManager/pull/345) that should fix it. It works fine for me. You can install this artifact:
https://github.com/YTVanced/VancedManager/suites/1795530480/artifacts/34407607
and report back. Also if you Manager reported that Vanced is already installed and was showing you reinstall button instead of install, it just changed its name in app drawer to com.google.youtube with generic android icon. This should fix it for you in such case.

**Comment by asdsadsaasd12312132** [comment]
> > I only found the cause (restarting phone) not solution.
> 
> Whoops, you're right. I read it wrong, my fault. If it comes to these crashes, I made a [PR](https://github.com/YTVanced/VancedManager/pull/345) that should fix it. It works fine for me. You can install this artifact:
> https://github.com/YTVanced/VancedManager/suites/1795530480/artifacts/34407607
> and report back. Also if Manager reported that Vanced is already installed and was showing you reinstall button instead of install, it just changed its name in app drawer to com.google.youtube with generic android icon. This should fix it for you in such case.

Do I change Youtube Vanced's name or the Manager's name?

**Comment by kyelbek** [comment]
Remove current version of Vanced Manager, then install .apk from .zip provided. After that you can just press "reinstall" if you have root version currenty installed. If not, just remove non-root and install root version again. After that you can check if YouTube Vanced starts. If it does, try restarting your phone and check again. It should work no matter how many times you restart your phone from now on.

**Comment by asdsadsaasd12312132** [comment]
> Remove current version of Vanced Manager, then install .apk from .zip provided. After that you can just press "reinstall" if you have root version currenty installed. If not, just remove non-root and install root version again. After that you can check if YouTube Vanced starts. If it does, try restarting your phone and check again. It should work no matter how many times you restart your phone from now on.

I followed these steps but I have the issue of being unable to launch Youtube Vanced after restarting due to it crashing. The problem with losing my settings may have been fixed though since after restarting, the icon always reverts to stock Youtube icon but it did not in this case.

**Comment by kyelbek** [comment]
Hmm, can you take a logcat and attach it here/pastebin? I checked this exact build and works fine for me.

**Comment by asdsadsaasd12312132** [comment]
> Hmm, can you take a logcat and attach it here/pastebin? I checked this exact build and works fine for me.
I launched Youtube Vanced 3 times. The first time it crashed without an error prompt. The 2-3 time, it crashed with an error prompt. It's like this every time I restart my phone.
[logcat_01-11-2021_00-12-02.txt](https://github.com/YTVanced/Vanced/files/5792622/logcat_01-11-2021_00-12-02.txt)

**Comment by kyelbek** [comment]
Are you sure that Vanced got installed properly without any errors in Manager? You're missing some required libraries in your filesystem, which should be installed along with Vanced itself. And they were, because you were able to launch YT before rebooting. It could be an issue with your OS actually since you're using xposed from what can I see. I wasn't able to replicate this problem, even with preinstalled YouTube.

Try that from your PC:
`adb shell "su -c 'ls -l -R /data/app/com.google.android.*'" > %UserProfile%\Desktop\filelist.txt`
and post output file from your desktop here.

**Comment by asdsadsaasd12312132** [comment]
> Are you sure that Vanced got installed properly without any errors in Manager? You're missing some required libraries in your filesystem, which should be installed along with Vanced itself. And they were, because you were able to launch YT before rebooting. It could be an issue with your OS actually since you're using xposed from what can I see. I wasn't able to replicate this problem, even with preinstalled YouTube.
> 
> Try that from your PC:
> `adb shell "su -c 'ls -l -R /data/app/com.google.android.*'" > %UserProfile%\Desktop\filelist.txt`
> and post output file from your desktop here.

I installed Vanced Manager multiple times in the past and never got any errors. I am using the latest stock OnePlus 3 OS with Magisk Manager and [EdXposed](https://forum.xda-developers.com/t/edxposed-the-successor-of-xposed-oreo-pie-q.4070805/).
[filelist.txt](https://github.com/YTVanced/Vanced/files/5793439/filelist.txt)

**Comment by kyelbek** [comment]
Alright, you're missing parts of the app for some reason. Let's try this:
```
adb shell "su -c 'rm -r /data/app/com.google.android.youtube-*'"
```
which will remove both of YouTube directory leftovers, then try installing Vanced root again. Check if it opens properly and re-run the command from my previous post. Change name of the file to 1.txt for example. After that, reboot your device and in case it'll get broken again, run same command one more time but rename output to 2.txt this time, then attach both of them in here. If it'll be working fine after reboot, try rebooting one more time to check again. If it didn't break this time, post only 1.txt.

**Comment by asdsadsaasd12312132** [comment]
I get these errors when I try to run that command

rm: base.apk: Device or resource busy
rm: base.apk: Device or resource busy

**Comment by asdsadsaasd12312132** [comment]
I couldn't run the command, so I did this instead:

1. uninstall Youtube with Lucky Patcher
2. install Youtube Vanced with Vanced Manager

The bug causing the settings to be loss on restart has been fixed but there's a new problem. Every time I restart my phone Youtube is uninstalled completely and I have to reinstall it. I reinstalled it with Vanced Manager.

**Comment by kyelbek** [comment]
You sure you're using the debug build I linked earlier? Because this issue seems to be something that got fixed with it already.
Try again:
https://github.com/kyelbek/VancedManager/releases/download/test/app-debug.apk
Other people are giving positive reports so far. Also try uninstalling Vanced with the Manager app next time. I did some tests and it handles leftover directories pretty well.
So, if the answer is yes, some other app could be interfering. But since you was able to run it before just fine, it looks like you're using current version of app or need to increase mount script delay in Vanced Manager settings.

**Comment by asdsadsaasd12312132** [comment]
> You sure you're using the debug build I linked earlier? Because this issue seems to be something that got fixed with it already.
> Try again:
> https://github.com/kyelbek/VancedManager/releases/download/test/app-debug.apk
> Other people are giving positive reports so far. Also try uninstalling Vanced with the Manager app next time. I did some tests and it handles leftover directories pretty well.
> So, if the answer is yes, some other app could be interfering. But since you was able to run it before just fine, it looks like you're using current version of app or need to increase mount script delay in Vanced Manager settings.

I tested again with the apk you linked. I am definitely using the correct one because it has a different icon than the usual Vanced Manager. The issue seems to be caused by Vanced Manager because I only have the problem with Youtube uninstalling itself on reboot with Vanced Manager installed. Without installing Youtube Vanced at all and just Vanced Manager installed, the stock version of Youtube uninstalls itself on reboot. I uninstalled Vanced Manager and the problem stopped occurring.

**Comment by asdsadsaasd12312132** [comment]
I just tested setting the script delay to the maximum in Vanced Manager settings and I still had the same problem.

**Comment by kyelbek** [comment]
> Without installing Youtube Vanced at all and with just Vanced Manager installed, even the stock version of Youtube uninstalls itself on reboot. I uninstalled Vanced Manager and the problem stopped occurring.

Damn. To be honest, I don't know why is this happening for you. I tried different configurations to replicate the problem, I was able to get duped youtube folders once with no libs, .apk's stuck, like in your case earlier, and Vanced Managed have gotten past that with no problem.

For others that uninstall problem got solved with what I did:
https://github.com/YTVanced/VancedManager/issues/340
https://github.com/YTVanced/VancedManager/issues/322

Well, since you're saying that even keeping Vanced Manager on your phone is uninstalling stock YT, you can try installing Vanced and removing Manager afterwards. It's not needed at this point.
Also one thing. That delay you're setting, keep in mind that if you set value for example 120, you'll have to wait 120 seconds after your OS boots to access YT Vanced. If you try to open it earlier, stock YT will open. That might cause it to uninstall after next reboot.

If you decide to try again, pull this script for me after installing vanced:
adb pull /data/adb/service.d/vanced.sh > %UserProfile%\Desktop\vanced.sh

**Comment by gghhkm** [comment]
> I just tested setting the script delay to the maximum in Vanced Manager settings and I still had the same problem.

You shouldn't have it at Max, you know how much time that is? It's 50 seconds, I don't imagine your phone taking 50 seconds to boot up. 🗿 Set it between 1 and 10.
Also the next manager build to be released will fix root completely, so...

**Comment by asdsadsaasd12312132** [comment]
> > I just tested setting the script delay to the maximum in Vanced Manager settings and I still had the same problem.
> 
> You shouldn't have it at Max, you know how much time that is? It's 50 seconds, I don't imagine your phone taking 50 seconds to boot up. 🗿 Set it between 1 and 10.
> Also the next manager build to be released will fix root completely, so...

I had it on 1 originally. I just changed it to the maximum to test after kyelbek suggested increasing the mount time. I waited 5 minutes after booting before checking anyway.

I'll keep testing later. I have just been bust lately.

**Comment by asdsadsaasd12312132** [comment]
I got Youtube to appear but now my original problem is back (crashing on reboot). I had to restart my phone again for it to appear. Order of events:

1. install Youtube Vanced
2. reboot (Vanced disappears)
3. reboot (Vanced reappears but original problem occurs)
4. reboot (same thing)

Here are my logcat, filelist.txt, and vanced.sh at event 3.

[logcat_01-17-2021_22-52-57.txt](https://github.com/YTVanced/Vanced/files/5825991/logcat_01-17-2021_22-52-57.txt)
[filelist.txt](https://github.com/YTVanced/Vanced/files/5825989/filelist.txt)
[vanced.zip](https://github.com/YTVanced/Vanced/files/5825990/vanced.zip)

**Comment by asdsadsaasd12312132** [comment]
I checked my root directory and it seems I only have 46.13 MB of free space left (with Youtube Vanced and the Manager installed). Maybe this is the problem? I have 13 GB left on my internal storage though.

**Comment by kyelbek** [comment]
I don't see anything that would help in your logs, so you've got to wait for now. There are too much changes going on in Manager's root installer code, and I don't have time to follow it. What you can do for now is test new 2.2.1 official and keep your eyes open for new ones as another changes were made after that release too. Make sure you're not using Magisk 21.3 first tho. 21.2 and apparently 21.4 do work fine.

**Comment by asdsadsaasd12312132** [comment]
I solved the problem. Secure start-up must be disabled. Go to the settings to set your password, and click on change password. An option to about secure start-up will eventually appear. When it does, click no. I also changed my password to a pin and enabled the option to not require a ✓, but I don't know if that mattered.

Tested on:
Magisk v21.4
Vanced Manager v2.2.1
Youtube Vanced 15.32.32

I tested with both a 1 sec and 5 sec script sleep time and it worked with both.

**Comment by asdsadsaasd12312132** [comment]
It seems another cause is installing new Magisk modules. On the first restart, this issue will also be encountered.

**Comment by gghhkm** [comment]
>> I solved the problem. Secure start-up must be disabled. Go to the settings to set your password and click on change password. An option about secure start-up will eventually appear. When it does, click no. I also changed my password to a pin and enabled the option to not require a ✓, but I don't know if that mattered.

>>> Tested on:
>>> Magisk v21.4
>>> Vanced Manager v2.2.1
>>> Youtube Vanced 15.32.32

>I tested with both a 1 sec and 5 sec script sleep time and it worked with both.
> It seems another cause is installing new Magisk modules. On the first restart, this issue will also be encountered.

I think this is just an issue with the OnePlus 3, I have a OnePlus 6T and haven't seen anything from other oneplus users as of the newest manager release.
