### ISSUE TITLE
[Bug] Casting to TV/Chromecast does not work with 16.14.34 and above versions.

### ISSUE THREAD

**Issue by foreveryoungforty** [YTVanced/Vanced#688]
**Bug description**
The non-root version of YouTube Vanced doesn't work when casting to a TV/Chromecast. The same issue also applies to devices with original microG core with root version of YouTube Vanced/YouTube.

Users will receive an error as "YouTube won't run without Google play services" while some people will see "no devices found" in cast dialog. Both of the errors means the same and hence users should refer this issue for both cases instead of creating a duplicate. 
The original post is below created by the author of this issue:
>After updating to new version 16.14.34 the casting to internal chromecast of recent Sony Android TV does not work anymore, nor on external Chromecast 4K on a hdmi-port of same TV.
I get a spinner saying "searching for device".... and then "No device found". Casting worked perfect in earlier version(s) before update.
I tried all "tricks" of clearing cache and data, but no result.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01 and above 

**Android version**
Any Android version
>Android 11

**Device**
Any non-root device or a device with microG core
>Samsung Galaxy S10, also same issue on tablet Samsung Galaxy S6 

**Steps to Reproduce**

**Expected behavior**
Casting worked normally in earlier versions when clicking on the cast-icon, devices should appear.

_Attach images/videos if possible. These can be helpful in solving the issue._
> ![Screenshot_20210509-145859](https://user-images.githubusercontent.com/1782353/117588303-58405380-b0d7-11eb-9ccc-c59c2a88576d.jpg)

**Comment by natinusala** [comment]
Can confirm too on Oneplus 5T, Android 10, same non-root Vanced version. Casting worked fine on whatever previous version I had.

**Comment by stajne** [comment]
Can confirm on Xiaomi Mi A3 android 11. Worked fine before update

**Comment by lemkeant** [comment]
Pixel 4a, stock Android 11. No Chromecast option in the app but every other app, as well as the OS, work fine

**Comment by vemfanvet** [comment]
Same issue oneplus 7t Android 11

**Comment by NuggyBear** [comment]
Same.
Moto G7 Plus Android. 

Usually cast to Chromecast but it can't find the device at all. Netflix, Disney+, Prime and standard YouTube can all find it fine.

**Comment by Lynkzz** [comment]
Same issue here as well on a Pixel 5. Vanced doesn't detect any device, whether it be a Chromecast, console, or TV after the update.

**Comment by gghhkm** [comment]
New Open Beta program
Plz go apply.
https://discord.gg/nEY6kUR

**Comment by KevinX8** [comment]
hotfix pushed for chromecast on 16.14.34, redownload the same version to get it

**Comment by gghhkm** [comment]
bruh, who thumb downs a Collaborator when they tell you about an open beta. 😒

**Comment by natinusala** [comment]
I'm sorry the mobile version of GitHub doesn't show the Collaborator badge and your message atrociously looked like spam / phishing. My bad

**Comment by KevinX8** [comment]
lmao nah we do actually have a public beta thing now

**Comment by Lynkzz** [comment]
With the hotfix it now detects my Xbox but the other devices still don't show so it doesn't seem like it's been completely fixed.

**Comment by lemkeant** [comment]
Can anyone else confirm if this hotfix worked or not? I'd rather not upgrade until others can confirm it's fixed

**Comment by foreveryoungforty** [comment]
@KevinX8 indeed, over here with the hotfix (first update, then complete reinstall) , casting still does not work, does not find chromecast.
Still a spinner saying "searching for device".... and then "No device found".
Is it also possible to include the split_config.nl for Dutch , see Bug #686 . It is also not uploaded here : https://mirror.codebucket.de/vanced/api/v1/apks/v16.14.34/nonroot/Language/  (earlier versions always had it).
Thank you very much.

**Comment by natinusala** [comment]
@lemkeant it worked for my for my Chromecast

**Comment by KevinX8** [comment]
> @KevinX8 indeed, over here with the hotfix (first update, then complete reinstall) , casting still does not work, does not find chromecast.
> Still a spinner saying "searching for device".... and then "No device found".
> Is it also possible to include the split_config.nl for Dutch , see Bug #686 . It is also not uploaded here : https://mirror.codebucket.de/vanced/api/v1/apks/v16.14.34/nonroot/Language/ (earlier versions always had it).
> Thank you very much.

have you been using the mirror because I didn't push it to there yet, it's now pushed there, you can verify your base apk hashes:
black SHA-256: 32CA97BC0D81412C432424895C602428B16AF34D82D14AA31ABCE2A1D165231D
dark SHA-256: ABD5505A5B6380843ABB79445731066FE658669BE758EB12B1DEBCD2CC4B9E1E
another update will be pushed within a week or two that will address a few other issues people have been having so that's why the version number is unchanged, the splits used come directly from google via the playstore so if we didn't upload them it's because google didn't serve them for some reason, we'll see about them in the next update.

**Comment by gutobernardo** [comment]
I tried reinstalling after updating on my S10 an nothing changed as well

**Comment by KevinX8** [comment]
Check the sha256 of your base apk to confirm

**Comment by NuggyBear** [comment]
Hotfix didn't work for me

**Comment by KevinX8** [comment]
If it didn't work confirm you actually have it by checking the hash and also providing more details about your cast device(s)

**Comment by gutobernardo** [comment]
I reverted to previous version and then reinstalled the latest, now everything is working fine!

**Comment by foreveryoungforty** [comment]
> > @KevinX8 indeed, over here with the hotfix (first update, then complete reinstall) , casting still does not work, does not find chromecast.
> > Still a spinner saying "searching for device".... and then "No device found".
> > Is it also possible to include the split_config.nl for Dutch , see Bug #686 . It is also not uploaded here : https://mirror.codebucket.de/vanced/api/v1/apks/v16.14.34/nonroot/Language/ (earlier versions always had it).
> > Thank you very much.
> 
> have you been using the mirror because I didn't push it to there yet, it's now pushed there, you can verify your base apk hashes:
> black SHA-256: 32CA97BC0D81412C432424895C602428B16AF34D82D14AA31ABCE2A1D165231D
> dark SHA-256: ABD5505A5B6380843ABB79445731066FE658669BE758EB12B1DEBCD2CC4B9E1E
> another update will be pushed within a week or two that will address a few other issues people have been having so that's why the version number is unchanged, the splits used come directly from google via the playstore so if we didn't upload them it's because google didn't serve them for some reason, we'll see about them in the next update.

Yes, I used the most recent base.apk pushed this evening.
I have the built-in Chromecast (Chromecast Built-in (Android TV) 1.52.253741) on my Sony KD-65XF9005 4K and also Google Chromecast 4K on a HDMI-port. All my other apps work perfect with them, as did Vanced before the updates of today.

**Comment by KevinX8** [comment]
> > > @KevinX8 indeed, over here with the hotfix (first update, then complete reinstall) , casting still does not work, does not find chromecast.
> > > Still a spinner saying "searching for device".... and then "No device found".
> > > Is it also possible to include the split_config.nl for Dutch , see Bug #686 . It is also not uploaded here : https://mirror.codebucket.de/vanced/api/v1/apks/v16.14.34/nonroot/Language/ (earlier versions always had it).
> > > Thank you very much.
> > 
> > have you been using the mirror because I didn't push it to there yet, it's now pushed there, you can verify your base apk hashes:
> > black SHA-256: 32CA97BC0D81412C432424895C602428B16AF34D82D14AA31ABCE2A1D165231D
> > dark SHA-256: ABD5505A5B6380843ABB79445731066FE658669BE758EB12B1DEBCD2CC4B9E1E
> > another update will be pushed within a week or two that will address a few other issues people have been having so that's why the version number is unchanged, the splits used come directly from google via the playstore so if we didn't upload them it's because google didn't serve them for some reason, we'll see about them in the next update.
> 
> Yes, I used the most recent base.apk pushed this evening.
> I have the built-in Chromecast (Chromecast Built-in (Android TV) 1.52.253741) on my Sony KD-65XF9005 4K and also Google Chromecast 4K on a HDMI-port. All my other apps work perfect with them, as did Vanced before the updates of today.

Try do what the guy above just said, install it fresh

**Comment by foreveryoungforty** [comment]
I did it already both ways, update / then afterwards a complete fresh install, no result. I will give it a second chance....

**Comment by gutobernardo** [comment]
> I did it already both ways, update / then afterwards a complete fresh install, no result. I will give it a second chance....

try completely uninstalling the current version inside Vanced Manager and then installing again

**Comment by gghhkm** [comment]
@foreveryoungforty you could apply for the Open Beta use use the link from it. Should give you latest.

**Comment by JDMorris81** [comment]
No solution yet, not sure why this was closed

**Comment by gghhkm** [comment]
> No solution yet, not sure why this was closed

It's pinned so doesn't really matter.

**Comment by foreveryoungforty** [comment]
I did a fresh install, even with the new released microG from last evenin, and for some 15 minutes I thought I was there, it detected Chromocast. But after a few times leaving the app, theu were gone, and again 

> > I did it already both ways, update / then afterwards a complete fresh install, no result. I will give it a second chance....
> 
> try completely uninstalling the current version inside Vanced Manager and then installing again

I did a fresh install, even with the new released microG from last evening, and for some 15 minutes I thought I was there, it detected my Chromocast(s). But after a few times leaving the app, they were gone, and again a spinner saying "searching for device".... and then "No device found". I cleaned a second time and fresh installed with SAI, but same situation after some use of the app, devices no more detected.
I re-installed former version 16.02.35 now, and that works and casts great (and has also the dutch language file). So I'll wait for a future release in my case. Thanks for advice anyway.

**Comment by JDMorris81** [comment]
Clearing the app data seems to fix the issue temporarily but too much hassle to do before each use. Rolled back to previous version and I'll update again once fixed.

**Comment by natinusala** [comment]
Erratum : with the hotfix it detects the chromecast but refuses to cast 
(infinite spinner on the mobile, nothing happens on the chromecast 
display). It also shows an Android notification "Youtube Vanced will not 
work until you update Google Play Services" (rough translation).

**Comment by adWroc** [comment]
> > I did it already both ways, update / then afterwards a complete fresh install, no result. I will give it a second chance....
> 
> try completely uninstalling the current version inside Vanced Manager and then installing again

the method works but temporarily, after some time I get a message about the update of Google Play 
Servicess (they are up to date) and I cannot connect

**Comment by KevinX8** [comment]
Yes we noticed and we're not sure why, logcat didn't provide anything useful but I can confirm casting is broken in the same on stock microg too

**Comment by POIZ87** [comment]
Confirm that chrome cast won't work on OnePlus 8Pro
I get a notification to update google play services. But nothing happens there.

**Comment by osonsur1** [comment]
Still getting update play services error when casting.

v16.16.38

**Comment by KevinX8** [comment]
Yes it's one of the know issue, it's related to microg not vanced

**Comment by gghhkm** [comment]
> Still getting update play services error when casting.
> 
> v16.16.38
It says that it's not fixed In the chance log.

**Comment by osonsur1** [comment]
> > Still getting update play services error when casting.
> > v16.16.38
> 
> It says that it's not fixed In the change log.

I see. What version should I roll back to then?

**Comment by KevinX8** [comment]
Tbh just use stock YouTube for casting, vanced cannot block chrome cast ads so you lose nothing

**Comment by osonsur1** [comment]
> Tbh just use stock YouTube for casting, vanced cannot block chrome cast ads so you lose nothing

Fair point.

**Comment by Malachiasz** [comment]
Doesn't work on Pixel 5, Android 11.

**Comment by KevinX8** [comment]
> Doesn't work on Pixel 5, Android 11.
> @KevinX8 Cannot use stock youtube. I uninstalled it. Also it would be inconvenient, as I often watch something on smartphone and only half way decide to share it to the TV. Switching apps in such moment would require finding the same video and the progress.

Hmmm if you uninstalled it then I'm guessing you have root? Nothing stopping you using the root version of vanced then

**Comment by Malachiasz** [comment]
No, just deactivated. Uninstalled was a mental shortcut.

**Comment by JDMorris81** [comment]
16.16.38 is a separate issue that involves play services. You should reopen it

**Comment by KevinX8** [comment]
no it's the exact same issue, we did not do anything different in 16.16.38

**Comment by KevinX8** [comment]
Or just use stock YouTube for casting as vanced is not even designed around casting?

**Comment by POIZ87** [comment]
As long as there is a Version which casts i would never ever go back to stock YT. Did u open it lately? :D

By the why - thanks to all the develepers. I love Vanced :*

**Comment by noskap** [comment]
> Confirm that chrome cast won't work on OnePlus 8Pro
> I get a notification to update google play services. But nothing happens there.

Same issue here.

**Comment by JDMorris81** [comment]
> no it's the exact same issue, we did not do anything different in 16.16.38

It is different because now I can see my device listed when cast icon is pressed but now I get a message to update play services which is a continuous spinner after clicking the message link

**Comment by Queuecumber** [comment]
It definitely sounds like a new issue but if you want to consolidate the Chromecast problems into one thread that makes sense too

**Comment by ccmoradia** [comment]
how to downgrade on non-root

**Comment by JDMorris81** [comment]
To downgrade: Go to Vanced Manager, uninstall Vanced. Then click settings, clear downloaded files. Next, click install for Vanced, click on the version, a drop down menu should open with previous versions. Select the one you want and install.

**Comment by kanekv** [comment]
I agree with some previous commenters that casting to Chromecast as is doesn't give much as it doesn't disable the ads, but I wanted to use it with smart tube next, using link tv with the code and this also didn't work for me. It connected successfully but doesn't play.

**Comment by Frdmx** [comment]
The user experience switching to the official app for casting is terrible. The entire point of casting simplicity is to easily shift in the middle of the video back and forth.

I have downgraded to an old microg version and old vanced version but am finding that it does not work for long. Any tested combinations should work out?

**Comment by JDMorris81** [comment]
I only downgraded Vanced to version 16.02.35. Still using the latest version of Micro G and no issues with casting or playback.

**Comment by Malachiasz** [comment]
Same as above. Except that after downgrading to  16.02.35 youtube was not loading - white app and loding progress infinitely. So I had to downgrade to 15.x which loaded, and then updated to  16.02.35 which works great.

**Comment by Alyetama** [comment]
> > no it's the exact same issue, we did not do anything different in 16.16.38
> 
> It is different because now I can see my device listed when cast icon is pressed but now I get a message to update play services which is a continuous spinner after clicking the message link

I have the same issue.

**Comment by megamorphg** [comment]
I'm also having this issue with the latest Vanced.

I'm wondering if my issue is different though because I can cast but it gives me an error about updating carrier services.

I tried uninstalling all Vanced apps and microg and then reinstalling.

Also tried deactivating microg cloud registration... Is there a way to remove the registration id and then reinstall it maybe?

**Comment by Troutking** [comment]
From both android tablet and mobile there isn't possible to connect to chromecast. Waiting patiently for a new update where this is resolved. Not a big deal since vanced don't remove ads on chromecast...

**Comment by retorquere** [comment]
It is true that casting from vanced doesn't remove ads, but I don't usually open regular YouTube, so when I find something I want to cast, I would have to refind it in regular YT.

Maybe just even a link "open in YT" would mostly solve the problem, no idea how hard that would be.

**Comment by JDMorris81** [comment]
> It is true that casting from vanced doesn't remove ads, but I don't usually open regular YouTube, so when I find something I want to cast, I would have to refind it in regular YT.
> 
> Maybe just even a link "open in YT" would mostly solve the problem, no idea how hard that would be.

Or just fix whatever went wrong between 16.02.35 and 16.14.34

**Comment by jeromemeichelbeck** [comment]
> I'm also having this issue with the latest Vanced.
> 
> I'm wondering if my issue is different though because I can cast but it gives me an error about updating carrier services.
> 
> I tried uninstalling all Vanced apps and microg and then reinstalling.
> 
> Also tried deactivating microg cloud registration... Is there a way to remove the registration id and then reinstall it maybe?
> 
> ![Screenshot_20210509-145859](https://user-images.githubusercontent.com/1782353/117588303-58405380-b0d7-11eb-9ccc-c59c2a88576d.jpg)

I have the exact same issue on my new phone. Really annoying.

**Comment by milindgoel15** [comment]
Had to rename title cuz people don't bother to search and read

**Comment by flagg19** [comment]
Are the original issue and the `youtube vanced won't run unless you update google play services` issue related? I'm experiencing the second one on a OnePlus Nord with Oxygen OS 11.1.1.2. I don't have a chromecast, but I've tried on two different smart-tv where before 16.14.34 it was working (and now it gives me that error).

I'm asking because if they are related, the chromecast part of the title might be misleading, and if they are not maybe the second problem could be placed in a different/new issue.

**Comment by Racle** [comment]
My workaround for this issue: (works with Android tv / 2020 chromecast with Google tv)

1. Install [SmartTubeNext](https://github.com/yuliskov/SmartTubeNext)
2. Open SmartTubeNext settings and click "linked devices" or "connected devices" (IIRC this was the correct place) 
3. There you should have button "add new pair" or something like that. Click that and you should see numbers. 
4. Open vanced and click chromecast icon. There should be button "Link with tv code"
5. Link your phone and you are good to cast

Note: you need to have SmartTubeNext open on your tv before you can cast. 

As a bonus, SmartTubeNext has ad blocking and SponsorBlock which works when casting this way.

**Comment by milindgoel15** [comment]
> Are the original issue and the `youtube vanced won't run unless you update google play services` issue related? I'm experiencing the second one on a OnePlus Nord with Oxygen OS 11.1.1.2. I don't have a chromecast, but I've tried on two different smart-tv where before 16.14.34 it was working (and now it gives me that error).
> 
> I'm asking because if they are related, the chromecast part of the title might be misleading, and if they are not maybe the second problem could be placed in a different/new issue.

Sending the screenshot of error won't hurt.

**Comment by flagg19** [comment]
> > Are the original issue and the `youtube vanced won't run unless you update google play services` issue related? I'm experiencing the second one on a OnePlus Nord with Oxygen OS 11.1.1.2. I don't have a chromecast, but I've tried on two different smart-tv where before 16.14.34 it was working (and now it gives me that error).
> > I'm asking because if they are related, the chromecast part of the title might be misleading, and if they are not maybe the second problem could be placed in a different/new issue.
> 
> Sending the screenshot of error won't hurt.

There's not much to see other than the error message that I wrote, anyway a screenshot has been already posted by user @megamorphg 

> ![Screenshot_20210509-145859](https://user-images.githubusercontent.com/1782353/117588303-58405380-b0d7-11eb-9ccc-c59c2a88576d.jpg)

**Comment by milindgoel15** [comment]
That's the same error this issue talks about. Dunno why u are getting confused with other sort of Google Play services. This issue is already known here itself. Please don't report it again and again.

**Comment by DancingBlade1** [comment]
I have been having this same problem with my husband. We both have OnePlus phones (7 and 7pro) thease last 2 updates fucked the whole thing I cannot cast anymore to my tv. It says i need to update Google play??? To fix it and when i press to go it freezes? Pls fix this issue -.-  I thought this update newest update would have fixed the issue because the bug is already on your knowledge, but obviously not?

**Comment by milindgoel15** [comment]
It's not vanced bug. Instead of complaining and saying it doesn't work, it should have been fixed with new updates and all, help the microG team by fixing the issue for everyone. If you can't code, wait patiently without complaining about it.

Vanced team is trying to fix it in our vanced microG fork but that doesn't mean it's our issue to deal with.

**Comment by jeromemeichelbeck** [comment]
Yes it is?

**Comment by Ismael-GT** [comment]
Same problem her with the lastest version installed. "Update Google play Services"..

**Comment by Queuecumber** [comment]
> Had to rename title cuz people don't bother to search and read

> That's the same error this issue talks about. Dunno why u are getting confused

People are confused because the bug in the op presented itself as 

> I get a spinner saying "searching for device".... and then "No device found".

And the bug now presents as 

> youtube vanced won't run unless you update google play services

Since the error manifests differently it's understandable to be confused and think the original bug may have been fixed and this is a new bug which should be discussed in a new issue to keep your tracker clean.

You're asserting that it's the same bug and should be kept here though, which is sensible and it has already been discussed at length here, maybe updating the op would help reduce confusion?

Btw has anyone filed an issue with upstream micro g about this?

**Comment by milindgoel15** [comment]
>Btw has anyone filed an issue with upstream micro g about this?

Upstream microG already has many opened issues regarding casting. Opening one more will just result in duplicate

**Comment by Alyetama** [comment]
> It's not vanced bug. Instead of complaining and saying it doesn't work, it should have been fixed with new updates and all, help the microG team by fixing the issue for everyone. If you can't code, wait patiently without complaining about it.
> 
> Vanced team is trying to fix it in our vanced microG fork but that doesn't mean it's our issue to deal with.

It seems to me that people are simply reporting the issue.  If it's a bug that killed a major feature, then it is only reasonable for people to look it up and tell the developers that they're experiencing it too.

**Comment by milindgoel15** [comment]
There's a difference between reporting a bug and saying "pls fix this issue, it should be fixed by now with next updates" which you missed.

**Comment by jwoglom** [comment]
If this is a bug in microG could someone link the related issue from their tracker? That might help others who are replying in this thread asking for status updates be able to follow progress on this issue.

**Comment by meld-cp** [comment]
This one? https://github.com/YTVanced/VancedMicroG/issues/143

**Comment by maghuro** [comment]
YTV 16.16.38 - bug still exists, can't cast anything

**Comment by prat89** [comment]
bug still exists

**Comment by milindgoel15** [comment]
All these users who are saying "bug still exists", here's a question for you. When did we released an update which fixes this issue? Because there's no update released for such. So please read changelogs very carefully and only speak here if you read them. Otherwise don't flood here!!!

**Comment by KevinX8** [comment]
Please use https://vancedapp.com/tv , it supports casting with vanced and also blocks ads and adds sponsorblock to the TV app, if you cast to the stock YouTube app you will have ads and sponsors cannot be skipped, the application should be installed to the TV and used as a replacement for the YouTube TV app.

**Comment by milindgoel15** [comment]
MORE INFO:

The casting issue will likely never be fixed as the microg team have no plans to reverse engineer the V2 casting API as it's very locked down for security reasons. 

Please refer https://github.com/YTVanced/Vanced/issues/688#issuecomment-991976558.

For anyone on an old Chromecast that doesn't support android apps, please use the stock YouTube app, you will get ads no matter what you do anyway.

NOTE: People using Google Play services with root variant will have no issues with casting or anyone with any old versions of vanced.
